<a href="https://colab.research.google.com/github/Mirsha-RG/tallerprograma2/blob/projects/empresas_construccion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = "https://raw.githubusercontent.com/it-ces/Datasets/main/Plenas(cotizantes)-car%C3%A1tula-2020.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.shape

(2897, 36)

In [ ]:
df.columns

Index(['Punto de Entrada', 'Nombre Formulario', 'NIT', 'Fecha de Corte',
       'El Máximo Órgano Social aprobó distribuir utilidades del ejercicio inmediatamente anterior',
       'Valor de las utilidades decretadas en miles de pesos (ejercicio inmediatamente anterior)',
       'Razón social de la sociedad', 'Objeto social principal',
       'Clasificación Industrial Internacional Uniforme Versión 4 A.C (CIIU)',
       'Corte de cuentas según estatutos',
       'Fecha de constitución (Aaaa-Mm-Dd)',
       'Fecha de vencimiento (Aaaa-Mm-Dd)', 'Estado actual', 'Tipo societario',
       'La sociedad es',
       'Dirección de notificación judicial registrada en Cámara de Comercio',
       'Departamento de la dirección de notificación judicial',
       'Ciudad de la dirección de notificación judicial',
       'Dirección del domicilio', 'Departamento de la dirección del domicilio',
       'Ciudad de la dirección del domicilio', 'Teléfono del domicilio',
       'Celular corporativo', 'E-mail de la sociedad',
       'Matricula mercantil número',
       'Domicilio casa matriz sucursal de sociedad extranjera',
       'País del domicilio casa matriz sucursal de sociedad extranjera',
       'La compañía está obligada a tener Revisor fiscal?',
       'El Revisor fiscal pertenece a una firma?',
       'A que firma pertenece el Revisor Fiscal?',
       'Los estados finacieros estan acompañados del dictamen del Revisor fiscal?',
       'Concepto del Revisor fiscal en su informe',
       'Estos estados financieros presentan información reexpresada?',
       'La información reexpresada corresponde a:',
       'Reexpresión según normatividad que aplique',
       'La Entidad posee inversiones en subsidiarias, asociadas y/o negocios conjuntos?'],
      dtype='object')

In [ ]:
def extract(PALABRA):
  return PALABRA[0]

In [ ]:
df['sector'] = df['Clasificación Industrial Internacional Uniforme Versión 4 A.C (CIIU)'].apply(extract)

In [ ]:
df['sector'].value_counts()

sector
G    739
C    631
F    287
A    231
M    158
L    157
B    152
J    151
N    138
K    108
H     62
I     45
D     12
S     10
R     10
P      3
Q      2
E      1
Name: count, dtype: int64

In [ ]:
df['sector']

0       H
1       H
2       H
3       B
4       N
       ..
2892    A
2893    G
2894    K
2895    L
2896    J
Name: sector, Length: 2897, dtype: object

In [ ]:
df['construct'] = np.where(df['sector']=='F',1, 0)

In [ ]:
firms_construc  =  df['construct'].sum()

In [ ]:
firms_construc

np.int64(287)

In [ ]:
from statsmodels.stats.proportion import proportion_confint

In [ ]:
proportion_confint(firms_construc, df.shape[0], 0.05) # librería

(0.08818906216408454, 0.10994694059739285)

In [ ]:
p_hat  = firms_construc/df.shape[0]

In [ ]:
p_hat

np.float64(0.0990680013807387)

In [ ]:
from scipy.stats import norm
alpha  = 0.05
Z = 1- alpha/2
Z_alpha = norm.ppf(Z)
Z_alpha

np.float64(1.959963984540054)

In [ ]:
SE = ((p_hat * (1 - p_hat))/df.shape[0])**0.5
sup = p_hat  + Z_alpha * SE
low = p_hat - Z_alpha * SE
low, sup

(np.float64(0.08818906216408454), np.float64(0.10994694059739285))


Con una confianza del 95% elmtotal de empresas del sector constructor esta entre el 8 y 11 por ciento, es decir de 100 empresas entre 8 y 11 son de construccion.